//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by xpkDemo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_XPKDEMO_DIALOG              102
#define IDD_XPKPREVIEW                  103
#define IDD_XPKEDIT                     104
#define IDD_XPKADDMEDIA                 105
#define IDD_DIALOG_PICTURE_PROPERTY     106
#define IDD_IDD_ADDFILTEDIALOG          110
#define IDR_MAINFRAME                   128
#define IDD_MUSIC                       130
#define IDD_SUBTITLE                    131
#define IDD_APNG_RGBA                   132
#define IDD_DIALOG_MEDIA_PROPERTY       133
#define IDD_FILTER                      134
#define IDD_DIALOG1                     135
#define IDD_DIALOG2                     136
#define IDD_LOADIMAGE                   136
#define IDC_DISPLAY                     1000
#define IDC_BUTTON2                     1002
#define IDC_SHOW_PICTURE                1003
#define IDC_BUTTON7                     1003
#define IDC_BUTTON1                     1004
#define IDC_PAUSE                       1005
#define IDC_CLEARALLMEDIA               1005
#define IDC_STOP                        1006
#define IDC_DELETEMEDIA                 1006
#define IDC_BUTTON3                     1007
#define IDC_CLEAR_MEDIA                 1007
#define IDC_PLAY                        1008
#define IDC_SHOW_EDIAT_PICTURE          1009
#define IDC_TIME_START                  1016
#define IDC_TIME_END                    1017
#define IDC_EDIT                        1018
#define IDC_XPK_EDIT                    1018
#define IDC_EDIT_OUTPUT_PATH            1020
#define IDC_PROGRESS1                   1021
#define IDC_EDIT_TOP                    1021
#define IDC_EDIT_APNG_TIMELINE_END      1021
#define IDC_MEDIA_CLIP_3                1021
#define IDC_EDIT_RIGHT                  1022
#define IDC_MEDIA_CLIP_2                1022
#define IDC_STATIC_LEFT                 1023
#define IDC_STATIC_TOP                  1024
#define IDC_STATIC_RIGHT                1025
#define IDC_STATIC_BOTTOM               1026
#define IDC_EDIT_BOTTOM                 1027
#define IDC_MEDIA_CLIP_END_TIME_1       1027
#define IDC_EDIT_LEFT                   1028
#define IDC_MEDIA_CLIP_START_TIME_2     1028
#define IDC_STATIC_CLIP                 1029
#define IDC_MEDIA_CLIP_END_TIME_2       1029
#define IDC_MEDIA_CLIP_START_TIME_3     1030
#define IDC_MEDIA_CLIP_END_TIME_3       1031
#define IDC_TAB1                        1035
#define IDC_MUSIC_TIMELINE_START        1036
#define IDC_MUSIC_TIMELINE_END          1037
#define IDC_MUSIC_CUT_TIME_START        1038
#define IDC_MUSIC_CUT_TIME_END          1039
#define IDC_RADIO_MINGYUE               1040
#define IDC_MUSIC_PATH                  1041
#define IDC_RADIO_YU                    1042
#define IDC_CHOOSE_MUSIC                1043
#define IDC_MUSISC_SAVE                 1044
#define IDC_APNG_FINISH                 1045
#define IDC_CLEAR_ALL_MUSIC             1045
#define IDC_RADIO_FISH                  1046
#define IDC_DELETE_MUSIC                1046
#define IDC_RADIO_SNOW                  1047
#define IDC_RADIO_BLACK_LINE            1048
#define IDC_RADIO_LOVE                  1049
#define IDC_EDIT_APNG_TIMELINE_START    1052
#define IDC_SUBTITLE_FINISH             1053
#define IDC_COMBO1                      1058
#define IDC_BOLD                        1059
#define IDC_ITALICS                     1060
#define IDC_UNDERLINE                   1061
#define IDC_COMBO2                      1062
#define IDC_FONT_LEFT                   1063
#define IDC_FONT_RIGHT                  1064
#define IDC_SUBTITLE_TEXT               1065
#define IDC_FONT_TOP                    1066
#define IDC_FONT_BOTTOM                 1067
#define IDC_FONT_COLOR                  1068
#define IDC_CURRENT_COLOR               1069
#define IDC_FONT_TIMELINE_START         1070
#define IDC_FONT_TIMELINE_END           1071
#define IDC_EDIT_MEDIA_LEFT             1072
#define IDC_EDIT_MEDIA_TOP              1073
#define IDC_EDIT_MEDIA_RIGHT            1074
#define IDC_EDIT_MEDIA_BOTTOM           1075
#define IDC_EDIT_MEDIA_CUT_START        1076
#define IDC_EDIT_MEDIA_CUT_END          1077
#define IDC_EDIT_MEDIA_INALIENABLE_TIME 1078
#define IDC_MEDIA_CLIP_1                1080
#define IDC_CHECK1                      1081
#define IDC_MEDIA_CLIP_START_TIME_1     1082
#define IDC_MIGRATORY_BIRD              1082
#define IDC_CLOUD                       1083
#define IDC_EDIT_RESOLUTION             1084
#define IDC_OVERCAST                    1084
#define IDC_CLEAR_ALL_SUBTITLE          1085
#define IDC_CLOUD2                      1085
#define IDC_CLEAR_ALL_APNG              1086
#define IDC_SUNSET_GLOW                 1086
#define IDC_MEDIA_DISPLAY               1087
#define IDC_DELETE_APNG                 1087
#define IDC_MEDIA_CUT_END_TIME_STATIC   1088
#define IDC_LIST1                       1089
#define IDC_FLEETING_TIME               1090
#define IDC_FINISH                      1091
#define IDC_DUSK                        1092
#define IDC_STATIC_OUT_RESOLUTION       1092
#define IDC_HAWAIIAN_LSLANDS            1093
#define IDC_STATIC_OUTPUT_FILE          1093
#define IDC_DELETE                      1094

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1094
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
